server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp

mybatis:
  type-aliases-package: com.example.web01.app.dto
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    root: info